export const CHOOSE_LAYOUT = 'CHOOSE_LAYOUT';
export const CHOOSE_CALENDAR = 'CHOOSE_CALENDAR';
export const CHOOSE_LANGUAGE = 'CHOOSE_LANGUAGE';
export const CHOOSE_FIRSTDAY = 'CHOOSE_FIRSTDAY';
export const CHOOSE_DATEFORMAT = 'CHOOSE_DATEFORMAT';
export const CHOOSE_THEMECOLOR = 'CHOOSE_THEMECOLOR';
export const CHOOSE_TITLECOLOR = 'CHOOSE_TITLECOLOR';
export const CHOOSE_MESSAGECOLOR = 'CHOOSE_MESSAGECOLOR';