export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_DATELABEL = 'UPDATE_DATELABEL';
export const UPDATE_DATETITLE = 'UPDATE_DATETITLE';
export const UPDATE_TIMETITLE = 'UPDATE_TIMETITLE';
export const UPDATE_MESSAGETEXT = 'UPDATE_MESSAGETEXT';
