export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_DATE_LABEL = 'UPDATE_DATE_LABEL';
export const UPDATE_DATE_TITLE = 'UPDATE_DATE_TITLE';
export const UPDATE_TIME_TITLE = 'UPDATE_TIME_TITLE';
export const UPDATE_MESSAGE_TEXT = 'UPDATE_MESSAGE_TEXT';
